- name: Windows Test Playbook
  hosts: win
  tasks:
    - name: Remote Execute the mqsc files
      win_shell: |
        ipconfig
     register: scriptoutput
    - name: Script output
      debug: var=scriptoutput.stdout
