sudo: false
language: go
go:
- 1.12
- 1.13
- tip
install:
- make deps
- go build -o winrm-cli
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/modocache/gover
- go get gopkg.in/check.v1
script:
- make ci
after_script:
- $HOME/gopath/bin/goveralls -service="travis-ci" -coverprofile=profile.cov -repotoken $COVERALLS_TOKEN
matrix:
  allow_failures:
  - go: tip
env:
  global:
   - secure: "fsw+gOY5uoxoiyde6N72r3Z2+AR3n80eWwZtFUjq3WGLiAnH0quiD+kL411cWgBv+cM8WuLjkYuXRFdnNT2IV9DCBj8FEukBTuwxB+PJERiQzCpMw8ViWBzkGbWIQGjIOomFbQ2GORnZ/HcJlLMh4J2Ia0g48hAtDMiwKXf2i4ym+F5pcsL5p2QJmjg5DFvrDlE8Cq3OOlq0CG237EGtHaGYGVfSHEzBAvg1WmAcva8v4XNI0M/VsDW8qZwUQQQcNNXyQwWSOe6q5IQIx5Li4TpQRn2KP9mAWtX4BRnzM9kadxyjvVCqOy19ShKjQQJcZ77RUjLxYvnvxrkYVNLViRWoTMSoDv4wG0ftRqXHQpsDeO4A3UNtPyGC+ha9B9Cks9kpsXiQB/NG7prg1blKXZCbDuDp7dPHgPXghArxhezE5QyDoyHas10zMSosFtptf8YS/XxAOxYCN+GFTPW4eT7X+68/ENmHu5LqqY6gB+FYi5lyntF+B3Rs6qBxbXuLgRxF8f8K9wetwWHmPsDledOtzZiA0k380Yjx8uu4xTt2KLSY0UTpYHcUKuq/5uOa6GwZwx68Db6h6OZ7YqqH2X6zXyHa1O7CB7ZWJrGhwuPJJ65tQdIjhp834TpR6MABaUQEXSiVT5ldVs4r6wa2HnVirRNOFlktCGHjJpZu9uU="
   - GO111MODULE=on

